name: Docker Build, Scan, and Push

on:
  workflow_dispatch:

env:
  IMAGE_NAME: rajmanohar21/hello-sample

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev   # <-- tells Actions to use secrets from Dev env
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master   # explicitly checkout master

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest helloworld/.

  scan:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          trivy --version

      - name: Run Trivy Scan
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ env.IMAGE_NAME }}:latest

  push:
    runs-on: ubuntu-latest
    environment: Dev
    needs: scan
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:latest
